### ISSUE TITLE
Where should I travel in India?

### ISSUE THREAD

**Issue by sindresorhus** [arjunmayilvaganan/ama#1]
I want to travel to India next year. What places would you recommend?

**Comment by arjunmayilvaganan** [comment]
Well, first of all, I myself have never been out of my own state much. But, I'm pretty sure I'll start going around, backpacking in a year.

I'll mention few places within my state, [Tamil Nadu](https://en.wikipedia.org/wiki/Tamil_Nadu).

[Chennai](https://en.wikipedia.org/wiki/Chennai) - My Hometown.
[Featured in BBC's one among the 5 cities to live in](http://www.bbc.com/travel/story/20150116-living-in-2015s-hottest-cities).
![Chennai](https://upload.wikimedia.org/wikipedia/commons/d/d1/View-from-Marina-Beach-Lighthouse-Chennai-2.jpg)


[Kodaikanal](https://en.wikipedia.org/wiki/Kodaikanal)
![Kodaikanal](https://upload.wikimedia.org/wikipedia/commons/7/7f/Upper_Lake_vire_kodaikanal.jpg)


[Kanyakumari](https://en.wikipedia.org/wiki/Kanyakumari)
![Kanyakumari](https://upload.wikimedia.org/wikipedia/commons/1/1e/Vivekananda_Rock.jpg)


[Thanjavur](https://en.wikipedia.org/wiki/Thanjavur)
![Thanjavur](https://upload.wikimedia.org/wikipedia/commons/a/ae/02Thanjavur_PeruvudaiyarKovil.jpg)


[Mahabalipuram](https://en.wikipedia.org/wiki/Mahabalipuram)
![Mahabalipuram](https://upload.wikimedia.org/wikipedia/commons/a/a6/Mahabalipuram-beeldhowwerk.JPG)


[Ooty](https://en.wikipedia.org/wiki/Ooty)
![Ooty](https://c2.staticflickr.com/4/3659/3297241347_b8bd856b64_b.jpg)


[Rameswaram](https://en.wikipedia.org/wiki/Rameswaram)
![Rameswaram](https://upload.wikimedia.org/wikipedia/commons/2/28/Dudhsagar_falls_with_train.jpg)

**Comment by sharsque** [comment]
@sindresorhus Did the India trip happen? How did it go?
